//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndonTVMaster
    {
        public int id { get; set; }
        public string TVName { get; set; }
        public string IPAddress { get; set; }
        public string IsActive { get; set; }
    }
}
