//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndonTVDockMapping
    {
        public int id { get; set; }
        public Nullable<int> TVId { get; set; }
        public Nullable<int> DockNo { get; set; }
    }
}
