//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiErrorLog
    {
        public long Id { get; set; }
        public string ApiName { get; set; }
        public string HttpMethod { get; set; }
        public string ApiUrl { get; set; }
        public string ErrorCode { get; set; }
        public Nullable<int> HttpStatusCode { get; set; }
        public string ErrorReason { get; set; }
        public string OperatorMessage { get; set; }
        public string ExceptionMessage { get; set; }
        public string RequestBody { get; set; }
        public string UniqueId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
