//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiErrorMaster
    {
        public int Id { get; set; }
        public string ApiName { get; set; }
        public string HttpMethod { get; set; }
        public string ErrorCode { get; set; }
        public int HttpStatusCode { get; set; }
        public string ErrorReason { get; set; }
        public string OperatorMessage { get; set; }
        public string ApiUrl { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
