//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Location
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string HouseNo { get; set; }
        public string LayerNo { get; set; }
        public string RoadWayNo { get; set; }
        public int Layer { get; set; }
        public int Row { get; set; }
        public int Col { get; set; }
        public int Direction { get; set; }
        public int DirectionByRing { get; set; }
        public Nullable<int> IsUse { get; set; }
        public string LocationType { get; set; }
        public int State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<long> CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<long> UpdateUserId { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<long> CreateOrgId { get; set; }
        public string CreateOrgName { get; set; }
        public bool IsDelete { get; set; }
        public string RoadWayType { get; set; }
        public Nullable<int> IsVirtual { get; set; }
        public string StemGroupNo { get; set; }
    }
}
