//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsrsZone
    {
        public int Id { get; set; }
        public string Zone { get; set; }
        public string Name { get; set; }
        public Nullable<int> LocationFrom { get; set; }
        public Nullable<int> LocationTo { get; set; }
    }
}
