//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSLocationZoneMaster
    {
        public int Id { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string MovementType { get; set; }
        public int Priority { get; set; }
        public int ColumnFrom { get; set; }
        public int ColumnTo { get; set; }
        public int RowFrom { get; set; }
        public int RowTo { get; set; }
        public int LevelFrom { get; set; }
        public int LevelTo { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
