//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GELoadingView
    {
        public int MTransNo { get; set; }
        public string LocationName { get; set; }
        public int Layer { get; set; }
        public int Row { get; set; }
        public int Col { get; set; }
        public string ZoneCode { get; set; }
        public string ZoneName { get; set; }
        public string MovementType { get; set; }
        public Nullable<int> ZonePriority { get; set; }
        public string FGModel { get; set; }
        public string FGDesc { get; set; }
        public string FGCode { get; set; }
        public string PalletQr { get; set; }
        public string PalletNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LocaStatus { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DeleteStatus { get; set; }
        public string Cat { get; set; }
        public string status { get; set; }
        public Nullable<long> sequence { get; set; }
    }
}
