//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingTemp
    {
        public int MTransNo { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Shift { get; set; }
        public Nullable<int> PackingLineNo { get; set; }
        public string UniqueId { get; set; }
        public Nullable<int> PalletSrNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string FGModel { get; set; }
        public string FGModelDesc { get; set; }
        public string FGcode { get; set; }
        public Nullable<decimal> WeightTheo { get; set; }
        public string ScannedQr { get; set; }
        public string LocationName { get; set; }
        public Nullable<int> LocationNo { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public Nullable<short> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string UUID { get; set; }
        public Nullable<int> Station { get; set; }
        public string SerialCode { get; set; }
    }
}
