//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadingLog
    {
        public int MTransNo { get; set; }
        public Nullable<int> LoadLocationid { get; set; }
        public string LocationName { get; set; }
        public string PalletQR { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Shift { get; set; }
        public Nullable<int> PackingLineNo { get; set; }
        public string UniqueId { get; set; }
        public Nullable<int> PalletSrNo { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string FGModel { get; set; }
        public string FGDesc { get; set; }
        public string FGcode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string OperatorName { get; set; }
        public string ShiftSupervisor { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public string TaskId { get; set; }
        public short CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string DeleteStatus { get; set; }
        public string SerialCode { get; set; }
    }
}
