//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menulist
    {
        public int MTransNo { get; set; }
        public string ModuleType { get; set; }
        public Nullable<int> MSLNo { get; set; }
        public string ModuleName { get; set; }
        public string ModulePage { get; set; }
        public string ModuleLink { get; set; }
    }
}
