//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokaYokaQCTransaction
    {
        public long Id { get; set; }
        public string QRCode { get; set; }
        public string FGModel { get; set; }
        public string FGCode { get; set; }
        public string UniqueId { get; set; }
        public string PalletNumber { get; set; }
        public Nullable<decimal> ReceivedWeight { get; set; }
        public Nullable<decimal> ReceivedQuantity { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<decimal> ActualQuantity { get; set; }
        public Nullable<decimal> WeightDifference { get; set; }
        public Nullable<decimal> QuantityDifference { get; set; }
        public Nullable<decimal> WeightTolerance { get; set; }
        public Nullable<decimal> QuantityTolerance { get; set; }
        public string QCStatus { get; set; }
        public string MachineIP { get; set; }
        public string MachineResponse { get; set; }
        public Nullable<System.DateTime> ScannedAt { get; set; }
        public Nullable<System.DateTime> WeighedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
    }
}
