//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class S1947Entities : DbContext
    {
        public S1947Entities()
            : base("name=S1947Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AndonTVDockMapping> AndonTVDockMappings { get; set; }
        public virtual DbSet<AndonTVMaster> AndonTVMasters { get; set; }
        public virtual DbSet<ApiErrorLog> ApiErrorLogs { get; set; }
        public virtual DbSet<ApiErrorMaster> ApiErrorMasters { get; set; }
        public virtual DbSet<App_Location> App_Location { get; set; }
        public virtual DbSet<ASRSLocationZoneMaster> ASRSLocationZoneMasters { get; set; }
        public virtual DbSet<AsrsZone> AsrsZones { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<Errorlog> Errorlogs { get; set; }
        public virtual DbSet<GE> GEs { get; set; }
        public virtual DbSet<GoodsExisiting> GoodsExisitings { get; set; }
        public virtual DbSet<GoodsExisiting_old> GoodsExisiting_old { get; set; }
        public virtual DbSet<LiftStatusMaster> LiftStatusMasters { get; set; }
        public virtual DbSet<LoadingLog> LoadingLogs { get; set; }
        public virtual DbSet<LoadingTemp> LoadingTemps { get; set; }
        public virtual DbSet<Menulist> Menulists { get; set; }
        public virtual DbSet<Othermaster> Othermasters { get; set; }
        public virtual DbSet<PartMaster> PartMasters { get; set; }
        public virtual DbSet<shift_master> shift_master { get; set; }
        public virtual DbSet<ShuttleDtl> ShuttleDtls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaskDtl> TaskDtls { get; set; }
        public virtual DbSet<TaskReport> TaskReports { get; set; }
        public virtual DbSet<TaskStatusCode> TaskStatusCodes { get; set; }
        public virtual DbSet<UnloadedData> UnloadedDatas { get; set; }
        public virtual DbSet<UnloadingLog> UnloadingLogs { get; set; }
        public virtual DbSet<UnloadMaterialTemp> UnloadMaterialTemps { get; set; }
        public virtual DbSet<UnloadTemp> UnloadTemps { get; set; }
        public virtual DbSet<UserAuthorization> UserAuthorizations { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<WcsApiLog> WcsApiLogs { get; set; }
        public virtual DbSet<GoodsExisting> GoodsExistings { get; set; }
        public virtual DbSet<GELoadingView> GELoadingViews { get; set; }
        public virtual DbSet<vw_AgeingReport> vw_AgeingReport { get; set; }
        public virtual DbSet<vw_TransactionHistory> vw_TransactionHistory { get; set; }
        public virtual DbSet<vw_TransactionReport> vw_TransactionReport { get; set; }
        public virtual DbSet<PokaYokaQCTransaction> PokaYokaQCTransactions { get; set; }
    
        public virtual int InsertTaskDtl(Nullable<int> taskNo, string taskType, Nullable<int> priority, string palletNo, string sourceLocation, string destinationLocation, string taskStatus, Nullable<int> liftNo, string locatioNo, Nullable<int> taskSent, Nullable<System.DateTime> createdAt, Nullable<System.DateTime> startedAt, Nullable<System.DateTime> completedAt, string uUID, string serialCode)
        {
            var taskNoParameter = taskNo.HasValue ?
                new ObjectParameter("TaskNo", taskNo) :
                new ObjectParameter("TaskNo", typeof(int));
    
            var taskTypeParameter = taskType != null ?
                new ObjectParameter("TaskType", taskType) :
                new ObjectParameter("TaskType", typeof(string));
    
            var priorityParameter = priority.HasValue ?
                new ObjectParameter("Priority", priority) :
                new ObjectParameter("Priority", typeof(int));
    
            var palletNoParameter = palletNo != null ?
                new ObjectParameter("PalletNo", palletNo) :
                new ObjectParameter("PalletNo", typeof(string));
    
            var sourceLocationParameter = sourceLocation != null ?
                new ObjectParameter("SourceLocation", sourceLocation) :
                new ObjectParameter("SourceLocation", typeof(string));
    
            var destinationLocationParameter = destinationLocation != null ?
                new ObjectParameter("DestinationLocation", destinationLocation) :
                new ObjectParameter("DestinationLocation", typeof(string));
    
            var taskStatusParameter = taskStatus != null ?
                new ObjectParameter("TaskStatus", taskStatus) :
                new ObjectParameter("TaskStatus", typeof(string));
    
            var liftNoParameter = liftNo.HasValue ?
                new ObjectParameter("LiftNo", liftNo) :
                new ObjectParameter("LiftNo", typeof(int));
    
            var locatioNoParameter = locatioNo != null ?
                new ObjectParameter("LocatioNo", locatioNo) :
                new ObjectParameter("LocatioNo", typeof(string));
    
            var taskSentParameter = taskSent.HasValue ?
                new ObjectParameter("TaskSent", taskSent) :
                new ObjectParameter("TaskSent", typeof(int));
    
            var createdAtParameter = createdAt.HasValue ?
                new ObjectParameter("CreatedAt", createdAt) :
                new ObjectParameter("CreatedAt", typeof(System.DateTime));
    
            var startedAtParameter = startedAt.HasValue ?
                new ObjectParameter("StartedAt", startedAt) :
                new ObjectParameter("StartedAt", typeof(System.DateTime));
    
            var completedAtParameter = completedAt.HasValue ?
                new ObjectParameter("CompletedAt", completedAt) :
                new ObjectParameter("CompletedAt", typeof(System.DateTime));
    
            var uUIDParameter = uUID != null ?
                new ObjectParameter("UUID", uUID) :
                new ObjectParameter("UUID", typeof(string));
    
            var serialCodeParameter = serialCode != null ?
                new ObjectParameter("SerialCode", serialCode) :
                new ObjectParameter("SerialCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertTaskDtl", taskNoParameter, taskTypeParameter, priorityParameter, palletNoParameter, sourceLocationParameter, destinationLocationParameter, taskStatusParameter, liftNoParameter, locatioNoParameter, taskSentParameter, createdAtParameter, startedAtParameter, completedAtParameter, uUIDParameter, serialCodeParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result4> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result4>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result4> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result4>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
