//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskReport
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public string SerialCode { get; set; }
        public string StatusCode { get; set; }
        public string StautusMessage { get; set; }
        public string OperationType { get; set; }
    }
}
