//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskStatusCode
    {
        public int ID { get; set; }
        public string StatusId { get; set; }
        public string StatusMessage { get; set; }
        public string UUID { get; set; }
    }
}
