//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDtl
    {
        public int id { get; set; }
        public int TaskNo { get; set; }
        public string TaskType { get; set; }
        public Nullable<int> Priority { get; set; }
        public string PalletNo { get; set; }
        public string SourceLocation { get; set; }
        public string DestinationLocation { get; set; }
        public string TaskStatus { get; set; }
        public string LiftNo { get; set; }
        public string LocatioNo { get; set; }
        public Nullable<int> TaskSent { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> StartedAt { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string UUID { get; set; }
        public string SerialCode { get; set; }
    }
}
