//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnloadMaterialTemp
    {
        public int id { get; set; }
        public string InvoiceNo { get; set; }
        public string Customer { get; set; }
        public string Location { get; set; }
        public string Model { get; set; }
        public string SAPFGCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> VehicleSize { get; set; }
        public Nullable<int> EnteredQty { get; set; }
        public Nullable<int> AvailableQty { get; set; }
        public string TransporterName { get; set; }
        public Nullable<int> FLCQty { get; set; }
        public string VehicleRegNo { get; set; }
        public string VehicleSealNo { get; set; }
        public Nullable<int> DockNo { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Shift { get; set; }
        public string SupervisiorName { get; set; }
        public string MobileNoSupervisor { get; set; }
        public string DriverName { get; set; }
        public string MobileNoDriver { get; set; }
        public string SecurityName { get; set; }
        public string MobileNoSecurity { get; set; }
        public string status { get; set; }
        public Nullable<int> Station { get; set; }
        public string SerialCode { get; set; }
    }
}
