//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnloadingLog
    {
        public int MTransNo { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerName { get; set; }
        public string LocationofDelivery { get; set; }
        public string FGModel { get; set; }
        public string FGDesc { get; set; }
        public string FGCode { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> FLCLocation { get; set; }
        public Nullable<int> VehicleSize { get; set; }
        public string VehicleNumber { get; set; }
        public string TransporterName { get; set; }
        public Nullable<System.DateTime> LoadingstartTime { get; set; }
        public Nullable<System.DateTime> LoadingEndtime { get; set; }
        public string VehicleSealNo { get; set; }
        public Nullable<int> DockNo { get; set; }
        public Nullable<int> BoxQty { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public string PlalletSrNo { get; set; }
        public string PlalletQR { get; set; }
        public string LocationId { get; set; }
        public string LocationName { get; set; }
        public string SupervisiorName { get; set; }
        public string MobileNoSupervisor { get; set; }
        public string DriverName { get; set; }
        public string MobileNoDriver { get; set; }
        public string SecurityName { get; set; }
        public string MobileNoSecurity { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public short CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string SerialCode { get; set; }
    }
}
