//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AgeingReport
    {
        public Nullable<long> SrNo { get; set; }
        public string MaterialCode { get; set; }
        public string FGModel { get; set; }
        public string FGDesc { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string LocationName { get; set; }
        public int Col { get; set; }
        public string PalletNo { get; set; }
        public Nullable<System.DateTime> LoadedDate { get; set; }
        public Nullable<int> AgeDays { get; set; }
        public string LocaStatus { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
