//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransactionReport
    {
        public int MTransNo { get; set; }
        public string TransactionType { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.TimeSpan> TransactionTime { get; set; }
        public string Shift { get; set; }
        public string MaterialCode { get; set; }
        public string FGModel { get; set; }
        public string FGDesc { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string LocationName { get; set; }
        public string PalletQR { get; set; }
        public string OperatorName { get; set; }
        public string ShiftSupervisor { get; set; }
        public string InvoiceNo { get; set; }
        public string CustomerName { get; set; }
        public string VehicleNumber { get; set; }
        public string TransporterName { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public short CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
