//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1947.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WcsApiLog
    {
        public int Id { get; set; }
        public string ApiName { get; set; }
        public string RequestData { get; set; }
        public string ResponseData { get; set; }
        public Nullable<int> HttpStatusCode { get; set; }
        public Nullable<int> WcsCode { get; set; }
        public Nullable<bool> WcsStatus { get; set; }
        public string Result { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
